import { Creator, Video } from "./types";

export const INITIAL_CREATORS: Creator[] = [
  {
    id: "c1",
    name: "Marques Brownlee",
    avatar: "https://picsum.photos/seed/mkbhd/100/100",
  },
  {
    id: "c2",
    name: "Veritasium",
    avatar: "https://picsum.photos/seed/veritasium/100/100",
  },
  {
    id: "c3",
    name: "Cleo Abram",
    avatar: "https://picsum.photos/seed/cleo/100/100",
  },
];

export const INITIAL_VIDEOS: Video[] = [
  {
    id: "v1",
    title: "The Future of AI",
    url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    type: "mp4",
    creatorId: "c1",
    collaboratorIds: ["c2", "c3"],
    thumbnail: "https://picsum.photos/seed/ai/640/360",
    duration: "14:23",
    views: "1.2M",
    createdAt: "2023-10-25T10:00:00Z",
    rating: 4.8,
    weeklyViews: 150000,
    monthlyViews: 500000,
  },
  {
    id: "v2",
    title: "Why We Are Here",
    url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    type: "mp4",
    creatorId: "c2",
    thumbnail: "https://picsum.photos/seed/space/640/360",
    duration: "8:45",
    views: "850K",
    createdAt: "2023-11-02T14:30:00Z",
    rating: 4.5,
    weeklyViews: 80000,
    monthlyViews: 300000,
  },
  {
    id: "v3",
    title: "Quantum Computing Explained",
    url: "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    type: "mp4",
    creatorId: "c3",
    thumbnail: "https://picsum.photos/seed/quantum/640/360",
    duration: "21:10",
    views: "2.4M",
    createdAt: "2023-09-15T09:15:00Z",
    rating: 4.9,
    weeklyViews: 300000,
    monthlyViews: 900000,
  },
  {
    id: "v4",
    title: "Google Drive Video Example",
    url: "https://drive.google.com/file/d/1X2Y3Z4W5V6U7T8S9R0Q/preview",
    type: "gdrive",
    creatorId: "c1",
    thumbnail: "https://picsum.photos/seed/gdrive/640/360",
    duration: "5:30",
    views: "120K",
    createdAt: "2023-11-10T16:45:00Z",
    rating: 4.2,
    weeklyViews: 20000,
    monthlyViews: 50000,
  },
];
